spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: "jdbc:mysql://localhost:3306/demo"
    username: "root"
    password: "password"
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
  jackson:
    default-property-inclusion: NON_NULL
